### ISSUE TITLE
Wrong "called incorrect number of times" error when multiple expectations are registered on the same method

### ISSUE THREAD

**Issue by doudou** [jimweirich/flexmock#10]
First the error message ... which looks weird. It basically both says that a method has not been called, but this method signature can be found in the message list:

test_data_reader_creates_reader_on_associated_port(TC_RobyPlugin_TaskContext) [/home/doudou/dev/virgo/.gems/gems/flexmock-1.0.3/lib/flexmock/validators.rb:48]:
in mock 'mock for #Orocos::Spec::OutputPort:0x00000004196eb0': Method 'reader({:pull=>true, :type=>:buffer, :size=>20})' called incorrect number of times
1 call expected
0 matching calls found
The following messages have been received:
    to_ary()
    reader({:pull=>true, :type=>:buffer, :size=>20})

I set up two expectations on  reader:

The first one is a catch-all

  task.orogen_task.port("out").should_receive(:reader)

The second one is more specific

  task.orogen_task.port("out").should_receive(:reader).with({:pull => true, :type => :buffer, :size => 20}).once

If I comment the first one, the error is reported. Otherwise, the test passes fine.

**Comment by jimweirich** [comment]
The behavior is correct, but the error message is confusing.

Here's the deal. Expectations are matched in the order that they are declared. If you declare a more general match before a more specific match, the specific match will not be triggered.  So in your case, the catch-all reader expectation is preventing the second reader from ever triggering.

To fix this, either delete the first expectation or move it to after the second.

Regarding the error message, the call history records reader being called with the indicated hash, but it was matched by the catch-all, so it wasn't available for matching the "once" expectation.

Perhaps adding which expectation handled each call in the call history would clarify the problem  So your error message might look something like this:

<pre>
  1) Failure:
test_reader(BugTest) [/Users/jim/working/git/flexmock/lib/flexmock/validators.rb:62]:
in mock 'mock': Method 'reader({:pull=>true, :type=>:buffer, :size=>20})' called incorrect number of times
1 call expected
0 matching calls found
The following messages have been received:
    reader({:pull=>true, :type=>:buffer, :size=>20}) matched by should_receive(:reader)
</pre>

Thoughts?

**Comment by doudou** [comment]
Assuming that you don't want to change the behaviour ;-), changing the error message the way woo propose would do the trick, yes.

Having a specific section on expectation order in the documentation (which would describe by_default at the same time) would also be useful.

**Comment by jimweirich** [comment]
Hmm, you're right.  There needs to be a section on expectation matching order in the docs.  Thanks.

**Comment by jimweirich** [comment]
Version 1.0.4 updates the error messages as noted above and includes a description of matching order in the readme.
