### ISSUE TITLE
assert_block deprecated in minitest-2.12.0 and later

### ISSUE THREAD

**Issue by randycoulman** [jimweirich/flexmock#12]
In MiniTest 2.12.0, assert_block was deprecated.  Any expectation failure results in a deprecation warning coming from the super send at `test_unit_integration.rb:53`.

I had a brief look at how to fix it, but I wasn't sure of the best way to proceed.  It would be possible to replace the implementation of `TestFrameworkAdapter#assert_block` with something like this:

```
assert(yield, message)
```

But I'm not sure if that provides the desired error message or not.

I'd be happy to work on a pull request given a little direction of the best approach to take.

**Comment by randycoulman** [comment]
Update: assert_block was removed in minitest-4.6.0.

**Comment by jimweirich** [comment]
Thanks. It is fixed on HEAD.  I just need a to find a time to put together a release.

**Comment by randycoulman** [comment]
Awesome, thanks!  I should have looked at the commit history before updating.  Sorry 'bout that.
