### ISSUE TITLE
Flexmock 0.8.11 seems to require Ruby 1.9.x or greater, readme says 1.8.x or greater

### ISSUE THREAD

**Issue by gayle** [jimweirich/flexmock#3]
I installed Flexmock 0.8.11 and got the error 

```
    partial_mock.rb:94: syntax error, unexpected ',', expecting '|' (SyntaxError)
      define_method(method_name) { |*args, &block|
```

when trying to start up my server (See Full Stack Trace Below.) I am using Ruby 1.8.6.  I suspected the syntax error might be a difference between 1.8 and 1.9.  So I installed and tried it with Ruby 1.9.1 and the server started up OK.  

If there's an (easy) way to get it to work with Ruby 1.8 and 1.9, cool.  If not, then I'd just change your README.rdoc to specify that Ruby 1.9.x or greater is required for this version of Flexmock, because currently it says 1.8.x is OK.

(Note, I downgraded my flexmock to 0.8.6 and that works for now.  I don't know where the cutoff line for the Ruby 1.8 vs. 1.9 requirement between Flexmock 0.8.6 and 0.8.11.  I didn't try once I got something working again :) 

FULL STACK TRACE HERE:
c:/workspace/proctor_dev/vendor/rails/activesupport/lib/active_support/dependencies.rb:184:in `require': C:/Ruby/lib/ruby/gems/1.8/gems/flexmock-0.8.1
1/lib/flexmock/partial_mock.rb:94: syntax error, unexpected ',', expecting '|' (SyntaxError)
 define_method(method_name) { |*args, &block|
                                            ^
C:/Ruby/lib/ruby/gems/1.8/gems/flexmock-0.8.11/lib/flexmock/partial_mock.rb:101: syntax error, unexpected '}', expecting kEND
C:/Ruby/lib/ruby/gems/1.8/gems/flexmock-0.8.11/lib/flexmock/partial_mock.rb:295: syntax error, unexpected $end, expecting kEND
  from c:/workspace/proctor_dev/vendor/rails/activesupport/lib/active_support/dependencies.rb:184:in`require'
  from C:/Ruby/lib/ruby/gems/1.8/gems/flexmock-0.8.11/lib/flexmock/base.rb:22
  from c:/workspace/proctor_dev/vendor/rails/activesupport/lib/active_support/dependencies.rb:184:in `require'
  from c:/workspace/proctor_dev/vendor/rails/activesupport/lib/active_support/dependencies.rb:184:in`require'
  from C:/Ruby/lib/ruby/gems/1.8/gems/flexmock-0.8.11/lib/flexmock.rb:12
  from C:/Ruby/lib/ruby/gems/1.8/gems/bundler-1.0.0/lib/bundler/runtime.rb:64:in `require'
  from C:/Ruby/lib/ruby/gems/1.8/gems/bundler-1.0.0/lib/bundler/runtime.rb:64:in`require'
  from C:/Ruby/lib/ruby/gems/1.8/gems/bundler-1.0.0/lib/bundler/runtime.rb:62:in `each'
  ... 12 levels...
  from c:/workspace/proctor_dev/vendor/rails/activesupport/lib/active_support/dependencies.rb:182:in`require'
  from c:/workspace/proctor_dev/vendor/rails/railties/lib/commands/server.rb:84
  from script/server:3:in `require'
  from script/server:3

**Comment by jimweirich** [comment]
Moved to https://www.pivotaltracker.com/story/show/7596461.

BTW, Ruby 1.8.7 is ok with this.  I'll investigate what it takes to get it working with 1.8.6 again.
