### ISSUE TITLE
Object#methods(false) broken on new Rubies

### ISSUE THREAD

**Issue by julik** [jimweirich/flexmock#4]
I've found that new Rubies do not really love Object#methods(false) - it's not documented anymore, and delegates explode with it. Delegates that means also tempfiles and all the rest of the affair - which is actually pretty broken. Why don'y we replace it with singleton_methods? This gets rid of the problem.

I've filed an issue with ruby-core on delegates 
http://redmine.ruby-lang.org/issues/4882

but in the meantime I've prepared a handy commit for you here 
https://github.com/julik/flexmock/commit/4acea00677e7b558bd564ec7c7630f0b27d368ca

Here's what happens because of this problem:

  1) Error:
test_write_larger_than_max_swaps_tempfile(TestBufferIO):
ArgumentError: wrong number of arguments (1 for 0)
    /Users/julik/.rvm/gems/ruby-1.9.2-p180/gems/flexmock-0.9.0/lib/flexmock/partial_mock.rb:201:in `singleton?'
    /Users/julik/.rvm/gems/ruby-1.9.2-p180/gems/flexmock-0.9.0/lib/flexmock/partial_mock.rb:236:in`stow_existing_definition'
    /Users/julik/.rvm/gems/ruby-1.9.2-p180/gems/flexmock-0.9.0/lib/flexmock/partial_mock.rb:92:in `add_mock_method'
    /Users/julik/.rvm/gems/ruby-1.9.2-p180/gems/flexmock-0.9.0/lib/flexmock/partial_mock.rb:46:in`initialize'

Also, please be so kind to either fix your bug report form or disable the Issues tab here. Or both. Or disable the form and enable Issues. Or neither. Dunno.
http://www.picupine.com/629b3b8x

**Comment by jimweirich** [comment]
Fixed.
