### ISSUE TITLE
flexmock throws NameError when mocking a method created by method_missing and respond_to_missing?

### ISSUE THREAD

**Issue by coffeejunk** [jimweirich/flexmock#6]
_I tried to report this issue on http://onestepback.org/cgi-bin/bugs.cgi?project=flexmock but i can't get passed the 'Please supply a detailed description of the bug report.' guard, so I'll try it here again:_

When I mock a method that is created on the fly via `method_missing` and known to `respond_to?` because of the usage of `respond_to_missing?` (which got introduced with ruby 1.9) flexmock throws a `NameError` in the teardown once it is trying to realias the original methods. `lib/flexmock/partial_mock.rb:280:in 'alias_method'`

I changed your 'Creating Partial Mocks' example a bit, to show the exact error and the 'workaround' I came up with: https://gist.github.com/2368754

**Comment by jimweirich** [comment]
Fixed by Pull requests #7
